#!/bin/sh
### BEGIN INIT INFO
# Provides: network4g
# Required-Start: $local_fs
# Required-Stop: 
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start or stop the network4g.
### END INIT INFO


proc_path="/usr/local/sbin/"
proc_name="network4g"

start() 
{
	proc_suffix=".start"
	${proc_path}${proc_name}${proc_suffix}
}

stop()
{
	proc_suffix=".stop"
	${proc_path}${proc_name}${proc_suffix}
}

case "$1" in
start) 
    start
    ;;
stop)
    stop
    ;;

restart)
    stop
    start
    ;;

*)
    echo "Usage: $0 {start|stop|restart}"
    exit 0
    ;;
esac

exit 0